# Misc global config stuff

# World Y levels
top-y: 512                                  #MIRABILIS (512)
ocean-level: ${meta.yml:bottom-y} + 190     #MIRABILIS (190)
deepslate-top: ${meta.yml:bottom-y} + 71    #MIRABILIS (71)
deepslate-bottom: ${meta.yml:bottom-y} + 57 #MIRABILIS (57)
bedrock-top: ${meta.yml:bottom-y} + 4       #MIRABILIS (4)
bottom-y: 0                                 #MIRABILIS (0) as god intended

palette-slant-generic:
  - BLOCK:minecraft:stone: $meta.yml:top-y

palette-ocean-level-sand:
  - SAND: ${meta.yml:ocean-level} + 1

palette-underwater:
  - MUDDY_BEACH: ${meta.yml:ocean-level} - 1

palette-bottom: # Added to the bottom of every biome palette stack
  - DEEPSLATE: $meta.yml:deepslate-top
  - BEDROCK: $meta.yml:bedrock-top
  - BLOCK:minecraft:bedrock: $meta.yml:bottom-y

palette-bedrock: # Added to the bottom of every biome palette stack that uses its own deepslate palette
  - BEDROCK: $meta.yml:bedrock-top
  - BLOCK:minecraft:bedrock: $meta.yml:bottom-y
